/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import db.dbManager;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Cliente;
import models.Compras;

/**
 *
 * @author Asus
 */
public class ComprasForm extends javax.swing.JFrame {

    /**
     * Creates new form ComprasForm
     */
    private Cliente clienteActual;
    private Map<String, Double> preciosProductos = new HashMap<>();

    public ComprasForm() {
        initComponents();

        preciosProductos.put("Auriculares", 1200.00);
        preciosProductos.put("Mouse", 1000.00);
        preciosProductos.put("Teclado", 1300.00);
        preciosProductos.put("Monitor", 6000.00);
        preciosProductos.put("Silla", 3000.00);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cbTipodeCompra = new javax.swing.JComboBox<>();
        cbArticulo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotalGeneral = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        bntAgregarCompras = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnBuscarClientes = new javax.swing.JButton();
        spnCantidad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Cédula:");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setEnabled(false);

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCedula.setEnabled(false);

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Fecha:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Vendedor:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Tipo de Compra:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Artículo:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Cantidad:");

        txtVendedor.setBackground(new java.awt.Color(255, 255, 255));
        txtVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVendedor.setEnabled(false);

        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFecha.setEnabled(false);

        cbTipodeCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbTipodeCompra.setForeground(new java.awt.Color(204, 204, 204));
        cbTipodeCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Crédito", "Contado", "Cheque" }));

        cbArticulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbArticulo.setForeground(new java.awt.Color(204, 204, 204));
        cbArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Monitor", "Auriculares", "Teclado", "Mouse", "Silla", " " }));
        cbArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbArticuloActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Precio:");

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio.setEnabled(false);
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Total:");

        txtTotalGeneral.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalGeneral.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotalGeneral.setEnabled(false);

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Vendedor", "Artículo", "TipoCompra", "Cantidad", "Precio Unidad", "Monto"
            }
        ));
        jScrollPane1.setViewportView(tblCompras);

        bntAgregarCompras.setBackground(new java.awt.Color(51, 204, 255));
        bntAgregarCompras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bntAgregarCompras.setForeground(new java.awt.Color(255, 255, 255));
        bntAgregarCompras.setText("Agregar");
        bntAgregarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAgregarComprasActionPerformed(evt);
            }
        });

        bntCancelar.setBackground(new java.awt.Color(255, 51, 51));
        bntCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bntCancelar.setForeground(new java.awt.Color(255, 255, 255));
        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        btnImprimir.setBackground(new java.awt.Color(153, 153, 0));
        btnImprimir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("Imprimir");
        btnImprimir.setEnabled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnBuscarClientes.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscarClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarClientes.setText("Buscar Cliente");
        btnBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClientesActionPerformed(evt);
            }
        });

        spnCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(488, 488, 488)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(bntAgregarCompras)
                                .addGap(13, 13, 13))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(229, 229, 229)
                                            .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(71, 71, 71)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(cbTipodeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(22, 22, 22)
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 57, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(cbArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbTipodeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotalGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAgregarCompras)
                    .addComponent(bntCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void bntAgregarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAgregarComprasActionPerformed

        if (clienteActual == null) {
            JOptionPane.showMessageDialog(this, "Debe buscar un cliente primero.");
            return;
        }

        String cedula = clienteActual.getCedula();
        String nombre = txtNombre.getText().trim();
        String fecha = txtFecha.getText();
        String vendedor = txtVendedor.getText();
        String tipoCompra = cbTipodeCompra.getSelectedItem().toString();
        String articulo = cbArticulo.getSelectedItem().toString();
        int cantidad = (int) spnCantidad.getValue();
        Double precio = preciosProductos.get(articulo);

        if (precio == null || precio <= 0) {
            JOptionPane.showMessageDialog(this, "El artículo seleccionado no tiene un precio válido.");
            return;
        }

        if (articulo.equals("Seleccionar") || tipoCompra.equals("Seleccionar") || precio <= 0 || cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos correctamente.");
            return;
        }
        Compras compra = new Compras(cedula, nombre, fecha, vendedor, tipoCompra, articulo, cantidad, precio);

        boolean guardado = dbManager.guardarCompras(compra);

        if (guardado) {
            JOptionPane.showMessageDialog(this, "Compra registrada correctamente.");

            double totalGeneral = 0;
            DefaultTableModel model = (DefaultTableModel) tblCompras.getModel();
            model.addRow(new Object[]{
                compra.getFecha(),
                compra.getVendedor(),
                compra.getArticulo(),
                compra.getTipoCompra(),
                compra.getCantidad(),
                compra.getPrecioUnitario(),
                compra.getTotal()
            });

            for (int i = 0; i < model.getRowCount(); i++) {
                Object value = model.getValueAt(i, 6);
                if (value != null) {
                    totalGeneral += Double.parseDouble(value.toString());
                }
            }
            btnImprimir.setEnabled(true);

            txtTotalGeneral.setText(String.format("RD$%.2f", totalGeneral));

            cbArticulo.setSelectedIndex(0);
            spnCantidad.setValue(1);
            //txtPrecio.setText("");
            txtBuscar.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar la compra.");
        }


    }//GEN-LAST:event_bntAgregarComprasActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Imprimir Factura");

        int seleccion = fileChooser.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();

            try {
                if (tblCompras.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No hay registros para imprimir.");
                    return;
                }
                Imprimir(archivo);
                JOptionPane.showMessageDialog(this, "Factura generada correctamente.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al generar archivo: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClientesActionPerformed
        String cedula = txtBuscar.getText().trim();
        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una cédula para buscar.");
            return;
        }

        clienteActual = dbManager.buscarClientePorCedula(cedula);

        if (clienteActual != null) {
            txtCedula.setText(clienteActual.getCedula());
            txtNombre.setText(clienteActual.getNombre());
            LocalDate hoy = LocalDate.now();
            // txtFecha.setText(hoy.toString());
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            txtFecha.setText(hoy.format(formato));
            //Vendedores
            String[] vendedores = {"Helen Rosario", "Osamu Dazai", "José Santana", "María Rosales", "Suguru Geto",
                "Edward Acevedo", "Tommy Contreras"};
            String vendedor = vendedores[new Random().nextInt(vendedores.length)];
            txtVendedor.setText(vendedor);

            //setEnabled(false);
            txtBuscar.setText("");
            txtBuscar.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado. Regístrelo primero desde el menú principal.");
            txtNombre.setText("");
        }


    }//GEN-LAST:event_btnBuscarClientesActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
      
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void cbArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbArticuloActionPerformed
                String articuloSeleccionado = cbArticulo.getSelectedItem().toString();

        if (preciosProductos.containsKey(articuloSeleccionado)) {
            double precio = preciosProductos.get(articuloSeleccionado);
            txtPrecio.setText(String.format("%.2f", precio));
        } else {
            txtPrecio.setText("");
        }
    }//GEN-LAST:event_cbArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprasForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAgregarCompras;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton btnBuscarClientes;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> cbArticulo;
    private javax.swing.JComboBox<String> cbTipodeCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTotalGeneral;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables

    private void Imprimir(File archivo) throws IOException {

        try (PrintWriter writer = new PrintWriter(archivo)) {

            writer.println("Cédula     : " + clienteActual.getCedula() + "   Nombre: " + clienteActual.getNombre());
            writer.println();

            writer.println("------------------------------------------------------------------------------------------");
            writer.println("------Resumen Final-------");

            writer.println("------------------------------------------------------------------------------------------");
            writer.printf("%-14s %-14s %-13s %-14s %-10s %-12s %-12s\n",
                    "Fecha", "Vendedor", "Artículo", "Tipo Compra", "Cantidad", "Precio", "Monto");
            writer.println("------------------------------------------------------------------------------------------");

            DefaultTableModel model = (DefaultTableModel) tblCompras.getModel();
            double totalGeneral = 0;

            for (int i = 0; i < model.getRowCount(); i++) {
                String fecha = model.getValueAt(i, 0).toString();
                String vendedor = model.getValueAt(i, 1).toString();
                String articulo = model.getValueAt(i, 2).toString();
                String tipoCompra = model.getValueAt(i, 3).toString();
                String cantidad = model.getValueAt(i, 4).toString();
                String precio = model.getValueAt(i, 5).toString();
                String monto = model.getValueAt(i, 6).toString();

                totalGeneral += Double.parseDouble(monto);

                writer.printf("%-14s %-14s %-13s %-14s %-10s %-12s %-12s\n",
                        fecha, vendedor, articulo, tipoCompra, cantidad, precio, monto);
            }

            writer.println("------------------------------------------------------------------------------------------");
            writer.printf("%-14s %.2f\n", "Total:", totalGeneral);
            writer.println();

            writer.println("-------------------------------------------------------------------------------------------");
            writer.println("-----------Final-----------------");
        }
    }
}
